node-description: aipa node defined
version: 1.0
author: aipa

#node 

node-view:
     # nodeid=  sha256(string(node-view except id ))
     nodeID: 
     nodeName:
     kind: producer|chain|application
     updateTime:
     signInfo:
     nodePath:
    

#creator infomation

Owner:
    accountName:
    keystoreDir:  /path/mywallet
    officeurl: https://www.bo.org
   
#service information

serviceInfo:
   - chain-service:
        serviceName: chainservice
        chainID:  1
        endpoint: /chain/..
        
           
        #to do more info
        
        
   - storages-service:
        serviceName: xxx
        capacity: 100
        sla: 99
        storageType:  cloud|nas|raid
        endpoint:  
   - 
        
#deployment infomation

deployment:
    
   apiVersion: 
   kind: Deployment
   metadata:
   name: kube100-site
   template:
      metadata:
         labels:
         app: web
   spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: flaskapp-demo
          image: jcdemo/flaskapp
          ports:
           - containerPort: 5000
      VMs:
        -  vmID: 
            cpu: intel 4 core
            mem: 16G
            bandwith: 20m 


# p2p configuration

p2p:
      outerIp:
      outerPort:
      NAT:
          ip:
          port:
      maxtriveTimes: 20
      quality:
          timedelay:
          lossrate: 
      maxPeerNum:
      seedNodeList:
         
        
#security configuration

node-security:
     nodeVisiable:  true|false
     authRequied:  true|false
     connectionPermmtion: true|false
     sslEnable: true|false
     self-pubkey: xxxx
